INSERT IGNORE INTO word (voca, meaning, category, tier, created_at) VALUES
-- 비즈니스 (business)
('negotiate', '협상하다', 'business', 'BRONZE', NOW()),
('implement', '실행하다', 'business', 'BRONZE', NOW()),
('evaluate', '평가하다', 'business', 'BRONZE', NOW()),
('collaborate', '협력하다', 'business', 'BRONZE', NOW()),
('facilitate', '촉진하다', 'business', 'SILVER', NOW()),
('allocate', '배분하다', 'business', 'SILVER', NOW()),
('prioritize', '우선순위를 정하다', 'business', 'SILVER', NOW()),
('streamline', '간소화하다', 'business', 'SILVER', NOW()),
('delegate', '위임하다', 'business', 'GOLD', NOW()),
('consolidate', '통합하다', 'business', 'GOLD', NOW()),

-- 경제 (economy)
('revenue', '수익', 'economy', 'BRONZE', NOW()),
('deficit', '적자', 'economy', 'BRONZE', NOW()),
('inflation', '인플레이션', 'economy', 'BRONZE', NOW()),
('recession', '경기 침체', 'economy', 'SILVER', NOW()),
('depreciate', '가치가 떨어지다', 'economy', 'SILVER', NOW()),
('commodity', '상품', 'economy', 'SILVER', NOW()),
('expenditure', '지출', 'economy', 'SILVER', NOW()),
('subsidy', '보조금', 'economy', 'GOLD', NOW()),
('fiscal', '재정의', 'economy', 'GOLD', NOW()),
('monetary', '통화의', 'economy', 'GOLD', NOW()),

-- 여행 (travel)
('itinerary', '여행 일정', 'travel', 'BRONZE', NOW()),
('accommodation', '숙박', 'travel', 'BRONZE', NOW()),
('reservation', '예약', 'travel', 'BRONZE', NOW()),
('departure', '출발', 'travel', 'BRONZE', NOW()),
('destination', '목적지', 'travel', 'BRONZE', NOW()),
('transit', '환승', 'travel', 'SILVER', NOW()),
('customs', '세관', 'travel', 'SILVER', NOW()),
('baggage', '수하물', 'travel', 'SILVER', NOW()),
('voucher', '상품권, 증서', 'travel', 'SILVER', NOW()),
('excursion', '소풍, 당일치기 여행', 'travel', 'GOLD', NOW()),

-- 인사/HR (hr)
('candidate', '지원자', 'hr', 'BRONZE', NOW()),
('resume', '이력서', 'hr', 'BRONZE', NOW()),
('interview', '면접', 'hr', 'BRONZE', NOW()),
('promotion', '승진', 'hr', 'BRONZE', NOW()),
('compensation', '보상, 급여', 'hr', 'SILVER', NOW()),
('recruitment', '채용', 'hr', 'SILVER', NOW()),
('probation', '수습 기간', 'hr', 'SILVER', NOW()),
('termination', '계약 해지', 'hr', 'SILVER', NOW()),
('tenure', '재직 기간', 'hr', 'GOLD', NOW()),
('incentive', '인센티브', 'hr', 'GOLD', NOW()),

-- 마케팅 (marketing)
('campaign', '캠페인', 'marketing', 'BRONZE', NOW()),
('demographic', '인구 통계', 'marketing', 'BRONZE', NOW()),
('strategy', '전략', 'marketing', 'BRONZE', NOW()),
('branding', '브랜딩', 'marketing', 'SILVER', NOW()),
('consumer', '소비자', 'marketing', 'SILVER', NOW()),
('survey', '설문조사', 'marketing', 'SILVER', NOW()),
('launch', '출시하다', 'marketing', 'SILVER', NOW()),
('endorse', '지지하다, 홍보하다', 'marketing', 'GOLD', NOW()),
('penetrate', '침투하다', 'marketing', 'GOLD', NOW()),
('niche', '틈새 시장', 'marketing', 'GOLD', NOW());